<?php
return [
    [
        "name_en" => "Afghanistan",
        "name_ar" => "أفغانستان",
        "emoji" => "🇦🇫",
        "code" => "AF",
        "phone" => "93",
    ],
    [
        "name_en" => "Aland Islands",
        "name_ar" => "جزر آلاند",
        "emoji" => "🇦🇽",
        "code" => "AX",
        "phone" => "358",
    ],
    [
        "name_en" => "Albania",
        "name_ar" => "ألبانيا",
        "emoji" => "🇦🇱",
        "code" => "AL",
        "phone" => "355",
    ],
    [
        "name_en" => "Algeria",
        "name_ar" => "الجزائر",
        "emoji" => "🇩🇿",
        "code" => "DZ",
        "phone" => "213",
    ],
    [
        "name_en" => "American Samoa",
        "name_ar" => "ساموا الأمريكية",
        "emoji" => "🇦🇸",
        "code" => "AS",
        "phone" => "1684",
    ],
    [
        "name_en" => "Andorra",
        "name_ar" => "أندورا",
        "emoji" => "🇦🇩",
        "code" => "AD",
        "phone" => "376",
    ],
    [
        "name_en" => "Angola",
        "name_ar" => "أنغولا",
        "emoji" => "🇦🇴",
        "code" => "AO",
        "phone" => "244",
    ],
    [
        "name_en" => "Anguilla",
        "name_ar" => "أنغيلا",
        "emoji" => "🇦🇮",
        "code" => "AI",
        "phone" => "1264",
    ],
    [
        "name_en" => "Antarctica",
        "name_ar" => "أنتاركتيكا",
        "emoji" => "🇦🇶",
        "code" => "AQ",
        "phone" => "672",
    ],
    [
        "name_en" => "Antigua and Barbuda",
        "name_ar" => "أنتيغوا وبربودا",
        "emoji" => "🇦🇬",
        "code" => "AG",
        "phone" => "1268",
    ],
    [
        "name_en" => "Argentina",
        "name_ar" => "الأرجنتين",
        "emoji" => "🇦🇷",
        "code" => "AR",
        "phone" => "54",
    ],
    [
        "name_en" => "Armenia",
        "name_ar" => "أرمينيا",
        "emoji" => "🇦🇲",
        "code" => "AM",
        "phone" => "374",
    ],
    [
        "name_en" => "Aruba",
        "name_ar" => "أروبا",
        "emoji" => "🇦🇼",
        "code" => "AW",
        "phone" => "297",
    ],
    [
        "name_en" => "Australia",
        "name_ar" => "أستراليا",
        "emoji" => "🇦🇺",
        "code" => "AU",
        "phone" => "61",
    ],
    [
        "name_en" => "Austria",
        "name_ar" => "النمسا",
        "emoji" => "🇦🇹",
        "code" => "AT",
        "phone" => "43",
    ],
    [
        "name_en" => "Azerbaijan",
        "name_ar" => "أذربيجان",
        "emoji" => "🇦🇿",
        "code" => "AZ",
        "phone" => "994",
    ],
    [
        "name_en" => "Bahamas",
        "name_ar" => "جزر البهاما",
        "emoji" => "🇧🇸",
        "code" => "BS",
        "phone" => "1242",
    ],
    [
        "name_en" => "Bahrain",
        "name_ar" => "البحرين",
        "emoji" => "🇧🇭",
        "code" => "BH",
        "phone" => "973",
    ],
    [
        "name_en" => "Bangladesh",
        "name_ar" => "بنغلاديش",
        "emoji" => "🇧🇩",
        "code" => "BD",
        "phone" => "880",
    ],
    [
        "name_en" => "Barbados",
        "name_ar" => "بربادوس",
        "emoji" => "🇧🇧",
        "code" => "BB",
        "phone" => "1246",
    ],
    [
        "name_en" => "Belarus",
        "name_ar" => "بيلاروسيا",
        "emoji" => "🇧🇾",
        "code" => "BY",
        "phone" => "375",
    ],
    [
        "name_en" => "Belgium",
        "name_ar" => "بلجيكا",
        "emoji" => "🇧🇪",
        "code" => "BE",
        "phone" => "32",
    ],
    [
        "name_en" => "Belize",
        "name_ar" => "بليز",
        "emoji" => "🇧🇿",
        "code" => "BZ",
        "phone" => "501",
    ],
    [
        "name_en" => "Benin",
        "name_ar" => "بنين",
        "emoji" => "🇧🇯",
        "code" => "BJ",
        "phone" => "229",
    ],
    [
        "name_en" => "Bermuda",
        "name_ar" => "برمودا",
        "emoji" => "🇧🇲",
        "code" => "BM",
        "phone" => "1441",
    ],
    [
        "name_en" => "Bhutan",
        "name_ar" => "بوتان",
        "emoji" => "🇧🇹",
        "code" => "BT",
        "phone" => "975",
    ],
    [
        "name_en" => "Bolivia",
        "name_ar" => "بوليفيا",
        "emoji" => "🇧🇴",
        "code" => "BO",
        "phone" => "591",
    ],
    [
        "name_en" => "Bonaire, Sint Eustatius and Saba",
        "name_ar" => "بونير وسانت يوستاتيوس وسابا",
        "emoji" => "🇧🇶",
        "code" => "BQ",
        "phone" => "599",
    ],
    [
        "name_en" => "Bosnia and Herzegovina",
        "name_ar" => "البوسنة والهرسك",
        "emoji" => "🇧🇦",
        "code" => "BA",
        "phone" => "387",
    ],
    [
        "name_en" => "Botswana",
        "name_ar" => "بوتسوانا",
        "emoji" => "🇧🇼",
        "code" => "BW",
        "phone" => "267",
    ],
    [
        "name_en" => "Bouvet Island",
        "name_ar" => "جزيرة بوفيت",
        "emoji" => "🇧🇻",
        "code" => "BV",
        "phone" => "55",
    ],
    [
        "name_en" => "Brazil",
        "name_ar" => "البرازيل",
        "emoji" => "🇧🇷",
        "code" => "BR",
        "phone" => "55",
    ],
    [
        "name_en" => "British Indian Ocean Territory",
        "name_ar" => "إقليم المحيط البريطاني الهندي",
        "emoji" => "🇮🇴",
        "code" => "IO",
        "phone" => "246",
    ],
    [
        "name_en" => "Brunei Darussalam",
        "name_ar" => "بروناي دار السلام",
        "emoji" => "🇧🇳",
        "code" => "BN",
        "phone" => "673",
    ],
    [
        "name_en" => "Bulgaria",
        "name_ar" => "بلغاريا",
        "emoji" => "🇧🇬",
        "code" => "BG",
        "phone" => "359",
    ],
    [
        "name_en" => "Burkina Faso",
        "name_ar" => "بوركينا فاسو",
        "emoji" => "🇧🇫",
        "code" => "BF",
        "phone" => "226",
    ],
    [
        "name_en" => "Burundi",
        "name_ar" => "بوروندي",
        "emoji" => "🇧🇮",
        "code" => "BI",
        "phone" => "257",
    ],
    [
        "name_en" => "Cambodia",
        "name_ar" => "كمبوديا",
        "emoji" => "🇰🇭",
        "code" => "KH",
        "phone" => "855",
    ],
    [
        "name_en" => "Cameroon",
        "name_ar" => "الكاميرون",
        "emoji" => "🇨🇲",
        "code" => "CM",
        "phone" => "237",
    ],
    [
        "name_en" => "Canada",
        "name_ar" => "كندا",
        "emoji" => "🇨🇦",
        "code" => "CA",
        "phone" => "1",
    ],
    [
        "name_en" => "Cape Verde",
        "name_ar" => "الرأس الأخضر",
        "emoji" => "🇨🇻",
        "code" => "CV",
        "phone" => "238",
    ],
    [
        "name_en" => "Cayman Islands",
        "name_ar" => "جزر كايمان",
        "emoji" => "🇰🇾",
        "code" => "KY",
        "phone" => "1345",
    ],
    [
        "name_en" => "Central African Republic",
        "name_ar" => "جمهورية افريقيا الوسطى",
        "emoji" => "🇨🇫",
        "code" => "CF",
        "phone" => "236",
    ],
    [
        "name_en" => "Chad",
        "name_ar" => "تشاد",
        "emoji" => "🇹🇩",
        "code" => "TD",
        "phone" => "235",
    ],
    [
        "name_en" => "Chile",
        "name_ar" => "تشيلي",
        "emoji" => "🇨🇱",
        "code" => "CL",
        "phone" => "56",
    ],
    [
        "name_en" => "China",
        "name_ar" => "الصين",
        "emoji" => "🇨🇳",
        "code" => "CN",
        "phone" => "86",
    ],
    [
        "name_en" => "Christmas Island",
        "name_ar" => "جزيرة الكريسماس",
        "emoji" => "🇨🇽",
        "code" => "CX",
        "phone" => "61",
    ],
    [
        "name_en" => "Cocos (Keeling) Islands",
        "name_ar" => "جزر كوكوس (كيلينغ)",
        "emoji" => "🇨🇨",
        "code" => "CC",
        "phone" => "672",
    ],
    [
        "name_en" => "Colombia",
        "name_ar" => "كولومبيا",
        "emoji" => "🇨🇴",
        "code" => "CO",
        "phone" => "57",
    ],
    [
        "name_en" => "Comoros",
        "name_ar" => "جزر القمر",
        "emoji" => "🇰🇲",
        "code" => "KM",
        "phone" => "269",
    ],
    [
        "name_en" => "Congo",
        "name_ar" => "الكونغو",
        "emoji" => "🇨🇬",
        "code" => "CG",
        "phone" => "242",
    ],
    [
        "name_en" => "Congo, Democratic Republic of the Congo",
        "name_ar" => "الكونغو ، جمهورية الكونغو الديمقراطية",
        "emoji" => "🇨🇩",
        "code" => "CD",
        "phone" => "242",
    ],
    [
        "name_en" => "Cook Islands",
        "name_ar" => "جزر كوك",
        "emoji" => "🇨🇰",
        "code" => "CK",
        "phone" => "682",
    ],
    [
        "name_en" => "Costa Rica",
        "name_ar" => "كوستا ريكا",
        "emoji" => "🇨🇷",
        "code" => "CR",
        "phone" => "506",
    ],
    [
        "name_en" => "Cote D\'Ivoire",
        "name_ar" => "ساحل العاج",
        "emoji" => "🇨🇮",
        "code" => "CI",
        "phone" => "225",
    ],
    [
        "name_en" => "Croatia",
        "name_ar" => "كرواتيا",
        "emoji" => "🇭🇷",
        "code" => "HR",
        "phone" => "385",
    ],
    [
        "name_en" => "Cuba",
        "name_ar" => "كوبا",
        "emoji" => "🇨🇺",
        "code" => "CU",
        "phone" => "53",
    ],
    [
        "name_en" => "Curacao",
        "name_ar" => "كوراكاو",
        "emoji" => "🇨🇼",
        "code" => "CW",
        "phone" => "599",
    ],
    [
        "name_en" => "Cyprus",
        "name_ar" => "قبرص",
        "emoji" => "🇨🇾",
        "code" => "CY",
        "phone" => "357",
    ],
    [
        "name_en" => "Czech Republic",
        "name_ar" => "الجمهورية التشيكية",
        "emoji" => "🇨🇿",
        "code" => "CZ",
        "phone" => "420",
    ],
    [
        "name_en" => "Denmark",
        "name_ar" => "الدنمارك",
        "emoji" => "🇩🇰",
        "code" => "DK",
        "phone" => "45",
    ],
    [
        "name_en" => "Djibouti",
        "name_ar" => "جيبوتي",
        "emoji" => "🇩🇯",
        "code" => "DJ",
        "phone" => "253",
    ],
    [
        "name_en" => "Dominica",
        "name_ar" => "دومينيكا",
        "emoji" => "🇩🇲",
        "code" => "DM",
        "phone" => "1767",
    ],
    [
        "name_en" => "Dominican Republic",
        "name_ar" => "جمهورية الدومنيكان",
        "emoji" => "🇩🇴",
        "code" => "DO",
        "phone" => "1809",
    ],
    [
        "name_en" => "Ecuador",
        "name_ar" => "الاكوادور",
        "emoji" => "🇪🇨",
        "code" => "EC",
        "phone" => "593",
    ],
    [
        "name_en" => "Egypt",
        "name_ar" => "مصر",
        "emoji" => "🇪🇬",
        "code" => "EG",
        "phone" => "20",
    ],
    [
        "name_en" => "El Salvador",
        "name_ar" => "السلفادور",
        "emoji" => "🇸🇻",
        "code" => "SV",
        "phone" => "503",
    ],
    [
        "name_en" => "Equatorial Guinea",
        "name_ar" => "غينيا الإستوائية",
        "emoji" => "🇬🇶",
        "code" => "GQ",
        "phone" => "240",
    ],
    [
        "name_en" => "Eritrea",
        "name_ar" => "إريتريا",
        "emoji" => "🇪🇷",
        "code" => "ER",
        "phone" => "291",
    ],
    [
        "name_en" => "Estonia",
        "name_ar" => "إستونيا",
        "emoji" => "🇪🇪",
        "code" => "EE",
        "phone" => "372",
    ],
    [
        "name_en" => "Ethiopia",
        "name_ar" => "أثيوبيا",
        "emoji" => "🇪🇹",
        "code" => "ET",
        "phone" => "251",
    ],
    [
        "name_en" => "Falkland Islands (Malvinas)",
        "name_ar" => "جزر فوكلاند (مالفيناس)",
        "emoji" => "🇫🇰",
        "code" => "FK",
        "phone" => "500",
    ],
    [
        "name_en" => "Faroe Islands",
        "name_ar" => "جزر فاروس",
        "emoji" => "🇫🇴",
        "code" => "FO",
        "phone" => "298",
    ],
    [
        "name_en" => "Fiji",
        "name_ar" => "فيجي",
        "emoji" => "🇫🇯",
        "code" => "FJ",
        "phone" => "679",
    ],
    [
        "name_en" => "Finland",
        "name_ar" => "فنلندا",
        "emoji" => "🇫🇮",
        "code" => "FI",
        "phone" => "358",
    ],
    [
        "name_en" => "France",
        "name_ar" => "فرنسا",
        "emoji" => "🇫🇷",
        "code" => "FR",
        "phone" => "33",
    ],
    [
        "name_en" => "French Guiana",
        "name_ar" => "غيانا الفرنسية",
        "emoji" => "🇬🇫",
        "code" => "GF",
        "phone" => "594",
    ],
    [
        "name_en" => "French Polynesia",
        "name_ar" => "بولينيزيا الفرنسية",
        "emoji" => "🇵🇫",
        "code" => "PF",
        "phone" => "689",
    ],
    [
        "name_en" => "French Southern Territories",
        "name_ar" => "المناطق الجنوبية لفرنسا",
        "emoji" => "🇹🇫",
        "code" => "TF",
        "phone" => "262",
    ],
    [
        "name_en" => "Gabon",
        "name_ar" => "الجابون",
        "emoji" => "🇬🇦",
        "code" => "GA",
        "phone" => "241",
    ],
    [
        "name_en" => "Gambia",
        "name_ar" => "غامبيا",
        "emoji" => "🇬🇲",
        "code" => "GM",
        "phone" => "220",
    ],
    [
        "name_en" => "Georgia",
        "name_ar" => "جورجيا",
        "emoji" => "🇬🇪",
        "code" => "GE",
        "phone" => "995",
    ],
    [
        "name_en" => "Germany",
        "name_ar" => "ألمانيا",
        "emoji" => "🇩🇪",
        "code" => "DE",
        "phone" => "49",
    ],
    [
        "name_en" => "Ghana",
        "name_ar" => "غانا",
        "emoji" => "🇬🇭",
        "code" => "GH",
        "phone" => "233",
    ],
    [
        "name_en" => "Gibraltar",
        "name_ar" => "جبل طارق",
        "emoji" => "🇬🇮",
        "code" => "GI",
        "phone" => "350",
    ],
    [
        "name_en" => "Greece",
        "name_ar" => "اليونان",
        "emoji" => "🇬🇷",
        "code" => "GR",
        "phone" => "30",
    ],
    [
        "name_en" => "Greenland",
        "name_ar" => "الأرض الخضراء",
        "emoji" => "🇬🇱",
        "code" => "GL",
        "phone" => "299",
    ],
    [
        "name_en" => "Grenada",
        "name_ar" => "غرينادا",
        "emoji" => "🇬🇩",
        "code" => "GD",
        "phone" => "1473",
    ],
    [
        "name_en" => "Guadeloupe",
        "name_ar" => "جوادلوب",
        "emoji" => "🇬🇵",
        "code" => "GP",
        "phone" => "590",
    ],
    [
        "name_en" => "Guam",
        "name_ar" => "غوام",
        "emoji" => "🇬🇺",
        "code" => "GU",
        "phone" => "1671",
    ],
    [
        "name_en" => "Guatemala",
        "name_ar" => "غواتيمالا",
        "emoji" => "🇬🇹",
        "code" => "GT",
        "phone" => "502",
    ],
    [
        "name_en" => "Guernsey",
        "name_ar" => "غيرنسي",
        "emoji" => "🇬🇬",
        "code" => "GG",
        "phone" => "44",
    ],
    [
        "name_en" => "Guinea",
        "name_ar" => "غينيا",
        "emoji" => "🇬🇳",
        "code" => "GN",
        "phone" => "224",
    ],
    [
        "name_en" => "Guinea-Bissau",
        "name_ar" => "غينيا بيساو",
        "emoji" => "🇬🇼",
        "code" => "GW",
        "phone" => "245",
    ],
    [
        "name_en" => "Guyana",
        "name_ar" => "غيانا",
        "emoji" => "🇬🇾",
        "code" => "GY",
        "phone" => "592",
    ],
    [
        "name_en" => "Haiti",
        "name_ar" => "هايتي",
        "emoji" => "🇭🇹",
        "code" => "HT",
        "phone" => "509",
    ],
    [
        "name_en" => "Heard Island and McDonald Islands",
        "name_ar" => "قلب الجزيرة وجزر ماكدونالز",
        "emoji" => "🇭🇲",
        "code" => "HM",
        "phone" => "0",
    ],
    [
        "name_en" => "Holy See (Vatican City State)",
        "name_ar" => "الكرسي الرسولي (دولة الفاتيكان)",
        "emoji" => "🇻🇦",
        "code" => "VA",
        "phone" => "39",
    ],
    [
        "name_en" => "Honduras",
        "name_ar" => "هندوراس",
        "emoji" => "🇭🇳",
        "code" => "HN",
        "phone" => "504",
    ],
    [
        "name_en" => "Hong Kong",
        "name_ar" => "هونج كونج",
        "emoji" => "🇭🇰",
        "code" => "HK",
        "phone" => "852",
    ],
    [
        "name_en" => "Hungary",
        "name_ar" => "هنغاريا",
        "emoji" => "🇭🇺",
        "code" => "HU",
        "phone" => "36",
    ],
    [
        "name_en" => "Iceland",
        "name_ar" => "أيسلندا",
        "emoji" => "🇮🇸",
        "code" => "IS",
        "phone" => "354",
    ],
    [
        "name_en" => "India",
        "name_ar" => "الهند",
        "emoji" => "🇮🇳",
        "code" => "IN",
        "phone" => "91",
    ],
    [
        "name_en" => "Indonesia",
        "name_ar" => "إندونيسيا",
        "emoji" => "🇮🇩",
        "code" => "ID",
        "phone" => "62",
    ],
    [
        "name_en" => "Iran, Islamic Republic of",
        "name_ar" => "جمهورية إيران الإسلامية",
        "emoji" => "🇮🇷",
        "code" => "IR",
        "phone" => "98",
    ],
    [
        "name_en" => "Iraq",
        "name_ar" => "العراق",
        "emoji" => "🇮🇶",
        "code" => "IQ",
        "phone" => "964",
    ],
    [
        "name_en" => "Ireland",
        "name_ar" => "أيرلندا",
        "emoji" => "🇮🇪",
        "code" => "IE",
        "phone" => "353",
    ],
    [
        "name_en" => "Isle of Man",
        "name_ar" => "جزيرة آيل أوف مان",
        "emoji" => "🇮🇲",
        "code" => "IM",
        "phone" => "44",
    ],
    [
        "name_en" => "Israel",
        "name_ar" => "إسرائيل",
        "emoji" => "🇮🇱",
        "code" => "IL",
        "phone" => "972",
    ],
    [
        "name_en" => "Italy",
        "name_ar" => "إيطاليا",
        "emoji" => "🇮🇹",
        "code" => "IT",
        "phone" => "39",
    ],
    [
        "name_en" => "Jamaica",
        "name_ar" => "جامايكا",
        "emoji" => "🇯🇲",
        "code" => "JM",
        "phone" => "1876",
    ],
    [
        "name_en" => "Japan",
        "name_ar" => "اليابان",
        "emoji" => "🇯🇵",
        "code" => "JP",
        "phone" => "81",
    ],
    [
        "name_en" => "Jersey",
        "name_ar" => "جيرسي",
        "emoji" => "🇯🇪",
        "code" => "JE",
        "phone" => "44",
    ],
    [
        "name_en" => "Jordan",
        "name_ar" => "الأردن",
        "emoji" => "🇯🇴",
        "code" => "JO",
        "phone" => "962",
    ],
    [
        "name_en" => "Kazakhstan",
        "name_ar" => "كازاخستان",
        "emoji" => "🇰🇿",
        "code" => "KZ",
        "phone" => "7",
    ],
    [
        "name_en" => "Kenya",
        "name_ar" => "كينيا",
        "emoji" => "🇰🇪",
        "code" => "KE",
        "phone" => "254",
    ],
    [
        "name_en" => "Kiribati",
        "name_ar" => "كيريباتي",
        "emoji" => "🇰🇮",
        "code" => "KI",
        "phone" => "686",
    ],
    [
        "name_en" => "Korea, Democratic People\'s Republic of",
        "name_ar" => "كوريا، الجمهورية الشعبية الديمقراطية",
        "emoji" => "🇰🇵",
        "code" => "KP",
        "phone" => "850",
    ],
    [
        "name_en" => "Korea, Republic of",
        "name_ar" => "جمهورية كوريا",
        "emoji" => "🇰🇷",
        "code" => "KR",
        "phone" => "82",
    ],
    [
        "name_en" => "Kosovo",
        "name_ar" => "كوسوفو",
        "emoji" => "🇽🇰",
        "code" => "XK",
        "phone" => "381",
    ],
    [
        "name_en" => "Kuwait",
        "name_ar" => "الكويت",
        "emoji" => "🇰🇼",
        "code" => "KW",
        "phone" => "965",
    ],
    [
        "name_en" => "Kyrgyzstan",
        "name_ar" => "قيرغيزستان",
        "emoji" => "🇰🇬",
        "code" => "KG",
        "phone" => "996",
    ],
    [
        "name_en" => "Lao People\'s Democratic Republic",
        "name_ar" => "جمهورية لاو الديمقراطية الشعبية",
        "emoji" => "🇱🇦",
        "code" => "LA",
        "phone" => "856",
    ],
    [
        "name_en" => "Latvia",
        "name_ar" => "لاتفيا",
        "emoji" => "🇱🇻",
        "code" => "LV",
        "phone" => "371",
    ],
    [
        "name_en" => "Lebanon",
        "name_ar" => "لبنان",
        "emoji" => "🇱🇧",
        "code" => "LB",
        "phone" => "961",
    ],
    [
        "name_en" => "Lesotho",
        "name_ar" => "ليسوتو",
        "emoji" => "🇱🇸",
        "code" => "LS",
        "phone" => "266",
    ],
    [
        "name_en" => "Liberia",
        "name_ar" => "ليبيريا",
        "emoji" => "🇱🇷",
        "code" => "LR",
        "phone" => "231",
    ],
    [
        "name_en" => "Libyan Arab Jamahiriya",
        "name_ar" => "الجماهيرية العربية الليبية",
        "emoji" => "🇱🇾",
        "code" => "LY",
        "phone" => "218",
    ],
    [
        "name_en" => "Liechtenstein",
        "name_ar" => "ليختنشتاين",
        "emoji" => "🇱🇮",
        "code" => "LI",
        "phone" => "423",
    ],
    [
        "name_en" => "Lithuania",
        "name_ar" => "ليتوانيا",
        "emoji" => "🇱🇹",
        "code" => "LT",
        "phone" => "370",
    ],
    [
        "name_en" => "Luxembourg",
        "name_ar" => "لوكسمبورغ",
        "emoji" => "🇱🇺",
        "code" => "LU",
        "phone" => "352",
    ],
    [
        "name_en" => "Macao",
        "name_ar" => "ماكاو",
        "emoji" => "🇲🇴",
        "code" => "MO",
        "phone" => "853",
    ],
    [
        "name_en" => "Macedonia, the Former Yugoslav Republic of",
        "name_ar" => "مقدونيا ، جمهورية يوغوسلافيا السابقة",
        "emoji" => "🇲🇰",
        "code" => "MK",
        "phone" => "389",
    ],
    [
        "name_en" => "Madagascar",
        "name_ar" => "مدغشقر",
        "emoji" => "🇲🇬",
        "code" => "MG",
        "phone" => "261",
    ],
    [
        "name_en" => "Malawi",
        "name_ar" => "ملاوي",
        "emoji" => "🇲🇼",
        "code" => "MW",
        "phone" => "265",
    ],
    [
        "name_en" => "Malaysia",
        "name_ar" => "ماليزيا",
        "emoji" => "🇲🇾",
        "code" => "MY",
        "phone" => "60",
    ],
    [
        "name_en" => "Maldives",
        "name_ar" => "جزر المالديف",
        "emoji" => "🇲🇻",
        "code" => "MV",
        "phone" => "960",
    ],
    [
        "name_en" => "Mali",
        "name_ar" => "مالي",
        "emoji" => "🇲🇱",
        "code" => "ML",
        "phone" => "223",
    ],
    [
        "name_en" => "Malta",
        "name_ar" => "مالطا",
        "emoji" => "🇲🇹",
        "code" => "MT",
        "phone" => "356",
    ],
    [
        "name_en" => "Marshall Islands",
        "name_ar" => "جزر مارشال",
        "emoji" => "🇲🇭",
        "code" => "MH",
        "phone" => "692",
    ],
    [
        "name_en" => "Martinique",
        "name_ar" => "مارتينيك",
        "emoji" => "🇲🇶",
        "code" => "MQ",
        "phone" => "596",
    ],
    [
        "name_en" => "Mauritania",
        "name_ar" => "موريتانيا",
        "emoji" => "🇲🇷",
        "code" => "MR",
        "phone" => "222",
    ],
    [
        "name_en" => "Mauritius",
        "name_ar" => "موريشيوس",
        "emoji" => "🇲🇺",
        "code" => "MU",
        "phone" => "230",
    ],
    [
        "name_en" => "Mayotte",
        "name_ar" => "مايوت",
        "emoji" => "🇾🇹",
        "code" => "YT",
        "phone" => "269",
    ],
    [
        "name_en" => "Mexico",
        "name_ar" => "المكسيك",
        "emoji" => "🇲🇽",
        "code" => "MX",
        "phone" => "52",
    ],
    [
        "name_en" => "Micronesia, Federated States of",
        "name_ar" => "ولايات ميكرونيزيا الموحدة",
        "emoji" => "🇫🇲",
        "code" => "FM",
        "phone" => "691",
    ],
    [
        "name_en" => "Moldova, Republic of",
        "name_ar" => "جمهورية مولدوفا",
        "emoji" => "🇲🇩",
        "code" => "MD",
        "phone" => "373",
    ],
    [
        "name_en" => "Monaco",
        "name_ar" => "موناكو",
        "emoji" => "🇲🇨",
        "code" => "MC",
        "phone" => "377",
    ],
    [
        "name_en" => "Mongolia",
        "name_ar" => "منغوليا",
        "emoji" => "🇲🇳",
        "code" => "MN",
        "phone" => "976",
    ],
    [
        "name_en" => "Montenegro",
        "name_ar" => "الجبل الأسود",
        "emoji" => "🇲🇪",
        "code" => "ME",
        "phone" => "382",
    ],
    [
        "name_en" => "Montserrat",
        "name_ar" => "مونتسيرات",
        "emoji" => "🇲🇸",
        "code" => "MS",
        "phone" => "1664",
    ],
    [
        "name_en" => "Morocco",
        "name_ar" => "المغرب",
        "emoji" => "🇲🇦",
        "code" => "MA",
        "phone" => "212",
    ],
    [
        "name_en" => "Mozambique",
        "name_ar" => "موزمبيق",
        "emoji" => "🇲🇿",
        "code" => "MZ",
        "phone" => "258",
    ],
    [
        "name_en" => "Myanmar",
        "name_ar" => "ميانمار",
        "emoji" => "🇲🇲",
        "code" => "MM",
        "phone" => "95",
    ],
    [
        "name_en" => "Namibia",
        "name_ar" => "ناميبيا",
        "emoji" => "🇳🇦",
        "code" => "NA",
        "phone" => "264",
    ],
    [
        "name_en" => "Nauru",
        "name_ar" => "ناورو",
        "emoji" => "🇳🇷",
        "code" => "NR",
        "phone" => "674",
    ],
    [
        "name_en" => "Nepal",
        "name_ar" => "نيبال",
        "emoji" => "🇳🇵",
        "code" => "NP",
        "phone" => "977",
    ],
    [
        "name_en" => "Netherlands",
        "name_ar" => "هولندا",
        "emoji" => "🇳🇱",
        "code" => "NL",
        "phone" => "31",
    ],
    [
        "name_en" => "Netherlands Antilles",
        "name_ar" => "جزر الأنتيل الهولندية",
        "emoji" => null,
        "code" => "AN",
        "phone" => "599",
    ],
    [
        "name_en" => "New Caledonia",
        "name_ar" => "كاليدونيا الجديدة",
        "emoji" => "🇳🇨",
        "code" => "NC",
        "phone" => "687",
    ],
    [
        "name_en" => "New Zealand",
        "name_ar" => "نيوزيلاندا",
        "emoji" => "🇳🇿",
        "code" => "NZ",
        "phone" => "64",
    ],
    [
        "name_en" => "Nicaragua",
        "name_ar" => "نيكاراغوا",
        "emoji" => "🇳🇮",
        "code" => "NI",
        "phone" => "505",
    ],
    [
        "name_en" => "Niger",
        "name_ar" => "النيجر",
        "emoji" => "🇳🇪",
        "code" => "NE",
        "phone" => "227",
    ],
    [
        "name_en" => "Nigeria",
        "name_ar" => "نيجيريا",
        "emoji" => "🇳🇬",
        "code" => "NG",
        "phone" => "234",
    ],
    [
        "name_en" => "Niue",
        "name_ar" => "نيوي",
        "emoji" => "🇳🇺",
        "code" => "NU",
        "phone" => "683",
    ],
    [
        "name_en" => "Norfolk Island",
        "name_ar" => "جزيرة نورفولك",
        "emoji" => "🇳🇫",
        "code" => "NF",
        "phone" => "672",
    ],
    [
        "name_en" => "Northern Mariana Islands",
        "name_ar" => "جزر مريانا الشمالية",
        "emoji" => "🇲🇵",
        "code" => "MP",
        "phone" => "1670",
    ],
    [
        "name_en" => "Norway",
        "name_ar" => "النرويج",
        "emoji" => "🇳🇴",
        "code" => "NO",
        "phone" => "47",
    ],
    [
        "name_en" => "Oman",
        "name_ar" => "سلطنة عمان",
        "emoji" => "🇴🇲",
        "code" => "OM",
        "phone" => "968",
    ],
    [
        "name_en" => "Pakistan",
        "name_ar" => "باكستان",
        "emoji" => "🇵🇰",
        "code" => "PK",
        "phone" => "92",
    ],
    [
        "name_en" => "Palau",
        "name_ar" => "بالاو",
        "emoji" => "🇵🇼",
        "code" => "PW",
        "phone" => "680",
    ],
    [
        "name_en" => "Palestinian Territory, Occupied",
        "name_ar" => "الأراضي الفلسطينية المحتلة",
        "emoji" => "🇵🇸",
        "code" => "PS",
        "phone" => "970",
    ],
    [
        "name_en" => "Panama",
        "name_ar" => "بنما",
        "emoji" => "🇵🇦",
        "code" => "PA",
        "phone" => "507",
    ],
    [
        "name_en" => "Papua New Guinea",
        "name_ar" => "بابوا غينيا الجديدة",
        "emoji" => "🇵🇬",
        "code" => "PG",
        "phone" => "675",
    ],
    [
        "name_en" => "Paraguay",
        "name_ar" => "باراغواي",
        "emoji" => "🇵🇾",
        "code" => "PY",
        "phone" => "595",
    ],
    [
        "name_en" => "Peru",
        "name_ar" => "بيرو",
        "emoji" => "🇵🇪",
        "code" => "PE",
        "phone" => "51",
    ],
    [
        "name_en" => "Philippines",
        "name_ar" => "فيلبيني",
        "emoji" => "🇵🇭",
        "code" => "PH",
        "phone" => "63",
    ],
    [
        "name_en" => "Pitcairn",
        "name_ar" => "بيتكيرن",
        "emoji" => "🇵🇳",
        "code" => "PN",
        "phone" => "64",
    ],
    [
        "name_en" => "Poland",
        "name_ar" => "بولندا",
        "emoji" => "🇵🇱",
        "code" => "PL",
        "phone" => "48",
    ],
    [
        "name_en" => "Portugal",
        "name_ar" => "البرتغال",
        "emoji" => "🇵🇹",
        "code" => "PT",
        "phone" => "351",
    ],
    [
        "name_en" => "Puerto Rico",
        "name_ar" => "بورتوريكو",
        "emoji" => "🇵🇷",
        "code" => "PR",
        "phone" => "1787",
    ],
    [
        "name_en" => "Qatar",
        "name_ar" => "دولة قطر",
        "emoji" => "🇶🇦",
        "code" => "QA",
        "phone" => "974",
    ],
    [
        "name_en" => "Reunion",
        "name_ar" => "جمع شمل",
        "emoji" => "🇷🇪",
        "code" => "RE",
        "phone" => "262",
    ],
    [
        "name_en" => "Romania",
        "name_ar" => "رومانيا",
        "emoji" => "🇷🇴",
        "code" => "RO",
        "phone" => "40",
    ],
    [
        "name_en" => "Russian Federation",
        "name_ar" => "الاتحاد الروسي",
        "emoji" => "🇷🇺",
        "code" => "RU",
        "phone" => "70",
    ],
    [
        "name_en" => "Rwanda",
        "name_ar" => "رواندا",
        "emoji" => "🇷🇼",
        "code" => "RW",
        "phone" => "250",
    ],
    [
        "name_en" => "Saint Barthelemy",
        "name_ar" => "سانت بارتيليمي",
        "emoji" => "🇧🇱",
        "code" => "BL",
        "phone" => "590",
    ],
    [
        "name_en" => "Saint Helena",
        "name_ar" => "سانت هيلانة",
        "emoji" => "🇸🇭",
        "code" => "SH",
        "phone" => "290",
    ],
    [
        "name_en" => "Saint Kitts and Nevis",
        "name_ar" => "سانت كيتس ونيفيس",
        "emoji" => "🇰🇳",
        "code" => "KN",
        "phone" => "1869",
    ],
    [
        "name_en" => "Saint Lucia",
        "name_ar" => "القديسة لوسيا",
        "emoji" => "🇱🇨",
        "code" => "LC",
        "phone" => "1758",
    ],
    [
        "name_en" => "Saint Martin",
        "name_ar" => "القديس مارتن",
        "emoji" => "🇲🇫",
        "code" => "MF",
        "phone" => "590",
    ],
    [
        "name_en" => "Saint Pierre and Miquelon",
        "name_ar" => "سانت بيير وميكلون",
        "emoji" => "🇵🇲",
        "code" => "PM",
        "phone" => "508",
    ],
    [
        "name_en" => "Saint Vincent and the Grenadines",
        "name_ar" => "سانت فنسنت وجزر غرينادين",
        "emoji" => "🇻🇨",
        "code" => "VC",
        "phone" => "1784",
    ],
    [
        "name_en" => "Samoa",
        "name_ar" => "ساموا",
        "emoji" => "🇼🇸",
        "code" => "WS",
        "phone" => "684",
    ],
    [
        "name_en" => "San Marino",
        "name_ar" => "سان مارينو",
        "emoji" => "🇸🇲",
        "code" => "SM",
        "phone" => "378",
    ],
    [
        "name_en" => "Sao Tome and Principe",
        "name_ar" => "ساو تومي وبرينسيبي",
        "emoji" => "🇸🇹",
        "code" => "ST",
        "phone" => "239",
    ],
    [
        "name_en" => "Saudi Arabia",
        "name_ar" => "المملكة العربية السعودية",
        "emoji" => "🇸🇦",
        "code" => "SA",
        "phone" => "966",
    ],
    [
        "name_en" => "Senegal",
        "name_ar" => "السنغال",
        "emoji" => "🇸🇳",
        "code" => "SN",
        "phone" => "221",
    ],
    [
        "name_en" => "Serbia",
        "name_ar" => "صربيا",
        "emoji" => "🇷🇸",
        "code" => "RS",
        "phone" => "381",
    ],
    [
        "name_en" => "Seychelles",
        "name_ar" => "سيشيل",
        "emoji" => "🇸🇨",
        "code" => "SC",
        "phone" => "248",
    ],
    [
        "name_en" => "Sierra Leone",
        "name_ar" => "سيرا ليون",
        "emoji" => "🇸🇱",
        "code" => "SL",
        "phone" => "232",
    ],
    [
        "name_en" => "Singapore",
        "name_ar" => "سنغافورة",
        "emoji" => "🇸🇬",
        "code" => "SG",
        "phone" => "65",
    ],
    [
        "name_en" => "St Martin",
        "name_ar" => "سينت مارتن",
        "emoji" => "🇸🇽",
        "code" => "SX",
        "phone" => "1",
    ],
    [
        "name_en" => "Slovakia",
        "name_ar" => "سلوفاكيا",
        "emoji" => "🇸🇰",
        "code" => "SK",
        "phone" => "421",
    ],
    [
        "name_en" => "Slovenia",
        "name_ar" => "سلوفينيا",
        "emoji" => "🇸🇮",
        "code" => "SI",
        "phone" => "386",
    ],
    [
        "name_en" => "Solomon Islands",
        "name_ar" => "جزر سليمان",
        "emoji" => "🇸🇧",
        "code" => "SB",
        "phone" => "677",
    ],
    [
        "name_en" => "Somalia",
        "name_ar" => "الصومال",
        "emoji" => "🇸🇴",
        "code" => "SO",
        "phone" => "252",
    ],
    [
        "name_en" => "South Africa",
        "name_ar" => "جنوب أفريقيا",
        "emoji" => "🇿🇦",
        "code" => "ZA",
        "phone" => "27",
    ],
    [
        "name_en" => "South Georgia and the South Sandwich Islands",
        "name_ar" => "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
        "emoji" => "🇬🇸",
        "code" => "GS",
        "phone" => "500",
    ],
    [
        "name_en" => "South Sudan",
        "name_ar" => "جنوب السودان",
        "emoji" => "🇸🇸",
        "code" => "SS",
        "phone" => "211",
    ],
    [
        "name_en" => "Spain",
        "name_ar" => "إسبانيا",
        "emoji" => "🇪🇸",
        "code" => "ES",
        "phone" => "34",
    ],
    [
        "name_en" => "Sri Lanka",
        "name_ar" => "سيريلانكا",
        "emoji" => "🇱🇰",
        "code" => "LK",
        "phone" => "94",
    ],
    [
        "name_en" => "Sudan",
        "name_ar" => "السودان",
        "emoji" => "🇸🇩",
        "code" => "SD",
        "phone" => "249",
    ],
    [
        "name_en" => "Suriname",
        "name_ar" => "سورينام",
        "emoji" => "🇸🇷",
        "code" => "SR",
        "phone" => "597",
    ],
    [
        "name_en" => "Svalbard and Jan Mayen",
        "name_ar" => "سفالبارد وجان ماين",
        "emoji" => "🇸🇯",
        "code" => "SJ",
        "phone" => "47",
    ],
    [
        "name_en" => "Swaziland",
        "name_ar" => "سوازيلاند",
        "emoji" => "🇸🇿",
        "code" => "SZ",
        "phone" => "268",
    ],
    [
        "name_en" => "Sweden",
        "name_ar" => "السويد",
        "emoji" => "🇸🇪",
        "code" => "SE",
        "phone" => "46",
    ],
    [
        "name_en" => "Switzerland",
        "name_ar" => "سويسرا",
        "emoji" => "🇨🇭",
        "code" => "CH",
        "phone" => "41",
    ],
    [
        "name_en" => "Syrian Arab Republic",
        "name_ar" => "الجمهورية العربية السورية",
        "emoji" => "🇸🇾",
        "code" => "SY",
        "phone" => "963",
    ],
    [
        "name_en" => "Taiwan, Province of China",
        "name_ar" => "مقاطعة تايوان الصينية",
        "emoji" => "🇹🇼",
        "code" => "TW",
        "phone" => "886",
    ],
    [
        "name_en" => "Tajikistan",
        "name_ar" => "طاجيكستان",
        "emoji" => "🇹🇯",
        "code" => "TJ",
        "phone" => "992",
    ],
    [
        "name_en" => "Tanzania, United Republic of",
        "name_ar" => "جمهورية تنزانيا المتحدة",
        "emoji" => "🇹🇿",
        "code" => "TZ",
        "phone" => "255",
    ],
    [
        "name_en" => "Thailand",
        "name_ar" => "تايلاند",
        "emoji" => "🇹🇭",
        "code" => "TH",
        "phone" => "66",
    ],
    [
        "name_en" => "Timor-Leste",
        "name_ar" => "تيمور ليشتي",
        "emoji" => "🇹🇱",
        "code" => "TL",
        "phone" => "670",
    ],
    [
        "name_en" => "Togo",
        "name_ar" => "توجو",
        "emoji" => "🇹🇬",
        "code" => "TG",
        "phone" => "228",
    ],
    [
        "name_en" => "Tokelau",
        "name_ar" => "توكيلاو",
        "emoji" => "🇹🇰",
        "code" => "TK",
        "phone" => "690",
    ],
    [
        "name_en" => "Tonga",
        "name_ar" => "تونغا",
        "emoji" => "🇹🇴",
        "code" => "TO",
        "phone" => "676",
    ],
    [
        "name_en" => "Trinidad and Tobago",
        "name_ar" => "ترينداد وتوباغو",
        "emoji" => "🇹🇹",
        "code" => "TT",
        "phone" => "1868",
    ],
    [
        "name_en" => "Tunisia",
        "name_ar" => "تونس",
        "emoji" => "🇹🇳",
        "code" => "TN",
        "phone" => "216",
    ],
    [
        "name_en" => "Turkey",
        "name_ar" => "ديك رومى",
        "emoji" => "🇹🇷",
        "code" => "TR",
        "phone" => "90",
    ],
    [
        "name_en" => "Turkmenistan",
        "name_ar" => "تركمانستان",
        "emoji" => "🇹🇲",
        "code" => "TM",
        "phone" => "7370",
    ],
    [
        "name_en" => "Turks and Caicos Islands",
        "name_ar" => "جزر تركس وكايكوس",
        "emoji" => "🇹🇨",
        "code" => "TC",
        "phone" => "1649",
    ],
    [
        "name_en" => "Tuvalu",
        "name_ar" => "توفالو",
        "emoji" => "🇹🇻",
        "code" => "TV",
        "phone" => "688",
    ],
    [
        "name_en" => "Uganda",
        "name_ar" => "أوغندا",
        "emoji" => "🇺🇬",
        "code" => "UG",
        "phone" => "256",
    ],
    [
        "name_en" => "Ukraine",
        "name_ar" => "أوكرانيا",
        "emoji" => "🇺🇦",
        "code" => "UA",
        "phone" => "380",
    ],
    [
        "name_en" => "United Arab Emirates",
        "name_ar" => "الإمارات العربية المتحدة",
        "emoji" => "🇦🇪",
        "code" => "AE",
        "phone" => "971",
    ],
    [
        "name_en" => "United Kingdom",
        "name_ar" => "المملكة المتحدة",
        "emoji" => "🇬🇧",
        "code" => "GB",
        "phone" => "44",
    ],
    [
        "name_en" => "United States",
        "name_ar" => "الولايات المتحدة",
        "emoji" => "🇺🇸",
        "code" => "US",
        "phone" => "1",
    ],
    [
        "name_en" => "United States Minor Outlying Islands",
        "name_ar" => "جزر الولايات المتحدة البعيدة الصغرى",
        "emoji" => "🇺🇲",
        "code" => "UM",
        "phone" => "1",
    ],
    [
        "name_en" => "Uruguay",
        "name_ar" => "أوروغواي",
        "emoji" => "🇺🇾",
        "code" => "UY",
        "phone" => "598",
    ],
    [
        "name_en" => "Uzbekistan",
        "name_ar" => "أوزبكستان",
        "emoji" => "🇺🇿",
        "code" => "UZ",
        "phone" => "998",
    ],
    [
        "name_en" => "Vanuatu",
        "name_ar" => "فانواتو",
        "emoji" => "🇻🇺",
        "code" => "VU",
        "phone" => "678",
    ],
    [
        "name_en" => "Venezuela",
        "name_ar" => "فنزويلا",
        "emoji" => "🇻🇪",
        "code" => "VE",
        "phone" => "58",
    ],
    [
        "name_en" => "Viet Nam",
        "name_ar" => "فييت نام",
        "emoji" => "🇻🇳",
        "code" => "VN",
        "phone" => "84",
    ],
    [
        "name_en" => "Virgin Islands, British",
        "name_ar" => "جزر العذراء البريطانية",
        "emoji" => "🇻🇬",
        "code" => "VG",
        "phone" => "1284",
    ],
    [
        "name_en" => "Virgin Islands, U.s.",
        "name_ar" => "جزر فيرجن ، الولايات المتحدة",
        "emoji" => "🇻🇮",
        "code" => "VI",
        "phone" => "1340",
    ],
    [
        "name_en" => "Wallis and Futuna",
        "name_ar" => "واليس وفوتونا",
        "emoji" => "🇼🇫",
        "code" => "WF",
        "phone" => "681",
    ],
    [
        "name_en" => "Western Sahara",
        "name_ar" => "الصحراء الغربية",
        "emoji" => "🇪🇭",
        "code" => "EH",
        "phone" => "212",
    ],
    [
        "name_en" => "Yemen",
        "name_ar" => "اليمن",
        "emoji" => "🇾🇪",
        "code" => "YE",
        "phone" => "967",
    ],
    [
        "name_en" => "Zambia",
        "name_ar" => "زامبيا",
        "emoji" => "🇿🇲",
        "code" => "ZM",
        "phone" => "260",
    ],
    [
        "name_en" => "Zimbabwe",
        "name_ar" => "زيمبابوي",
        "emoji" => "🇿🇼",
        "code" => "ZW",
        "phone" => "263",
    ],
];
